version: '3.7'

services:
  nginx:
    container_name: Web_Server
    image: nginx:stable-alpine
    volumes:
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ${WORDPRESS_DATA_DIR}:/var/www/html
      - ${FASTCGI_CACHE_DIR}:/var/run/nginx
    ports:
      - "8080:80"
    depends_on:
      - wordpress
    restart: unless-stopped
    networks:
      private_net:
        ipv4_address: 172.18.1.1

  wordpress:
    container_name: WordPress
    image: wordpress:php7.4-fpm-alpine
    volumes:
      - ${WORDPRESS_DATA_DIR}:/var/www/html
      - ${FASTCGI_CACHE_DIR}:/var/www/html/cache
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      private_net:
        ipv4_address: 172.18.1.2

  db:
    container_name: DB
    image: mariadb:10.5
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: unless-stopped
    networks:
      private_net:
        ipv4_address: 172.18.1.4

networks:
  private_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/16